# Generated by Django 4.2.1 on 2023-05-09 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=6)),
                ('contact', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('age', models.IntegerField(max_length=4)),
                ('height', models.IntegerField(max_length=10)),
                ('weight', models.IntegerField(max_length=10)),
                ('address', models.CharField(max_length=500)),
            ],
        ),
    ]
