# Generated by Django 4.2.1 on 2023-05-10 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genzone', '0002_validatedoc_validateuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='aadhar',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register',
            name='password',
            field=models.CharField(default=2, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='register',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='register',
            name='height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='register',
            name='weight',
            field=models.IntegerField(),
        ),
    ]
