# Generated by Django 4.2.1 on 2023-05-10 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genzone', '0003_register_aadhar_register_password_alter_register_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='height',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='register',
            name='weight',
            field=models.CharField(max_length=5),
        ),
    ]
