# Generated by Django 4.2.1 on 2023-05-10 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genzone', '0004_alter_register_height_alter_register_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='ran',
            field=models.CharField(default=2, max_length=6),
            preserve_default=False,
        ),
    ]
