# Generated by Django 4.2.1 on 2023-05-10 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genzone', '0006_rename_ran_register_uniqueid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ValidateUser',
            new_name='ValidatePatient',
        ),
    ]
