# Generated by Django 4.2.1 on 2023-05-10 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genzone', '0009_rename_emailid_validatepatient_emailid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='validatepatient',
            old_name='emailid',
            new_name='email',
        ),
    ]
