# Generated by Django 4.2 on 2023-05-11 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genzone', '0013_doctorlogin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorlogin',
            old_name='docid',
            new_name='docId',
        ),
    ]
